export const dataSource = [
    {
        id: '1',
        number: '001',
        name: 'Allosaurus',
        classification: 'Predator',
        fleeRate: 0.1,
    },
    {
        id: '2',
        number: '002',
        name: 'Stegosaurus',
        classification: 'Herbivorous',
        fleeRate: 0.2,
    },
    {
        id: '3',
        number: '003',
        name: 'Spinosaurus',
        classification: 'Predator',
        fleeRate: 0.3,
    },
    {
        id: '4',
        number: '004',
        name: 'Heterodon',
        classification: 'Omnivores',
        fleeRate: 0.4,
    },
    {
        id: '5',
        number: '005',
        name: 'Evoplocephalus',
        classification: 'Herbivorous',
        fleeRate: 0.1,
    },
    {
        id: '6',
        number: '006',
        name: 'Carcharodon',
        classification: 'Predator',
        fleeRate: 0.2,
    },
    {
        id: '7',
        number: '007',
        name: 'Ankylosaurus',
        classification: 'Herbivorous',
        fleeRate: 0.3,
    },
    {
        id: '8',
        number: '008',
        name: 'Oviraptor',
        classification: 'Omnivores',
        fleeRate: 0.4,
    },
    {
        id: '9',
        number: '009',
        name: 'Giganotosaurus',
        classification: 'Predator',
        fleeRate: 0.2,
    },
    {
        id: '10',
        number: '010',
        name: 'Diplodocus',
        classification: 'Herbivorous',
        fleeRate: 0.1,
    },
    {
        id: '11',
        number: '011',
        name: 'Troodon',
        classification: 'Omnivores',
        fleeRate: 0.3,
    },
    {
        id: '12',
        number: '012',
        name: 'Tyrannosaurus',
        classification: 'Predator',
        fleeRate: 0.4,
    },
    {
        id: '13',
        number: '013',
        name: 'Triceratops',
        classification: 'Herbivorous',
        fleeRate: 0.1,
    },
    {
        id: '14',
        number: '014',
        name: 'Gallimimus',
        classification: 'Omnivores',
        fleeRate: 0.5,
    },
    {
        id: '15',
        number: '015',
        name: 'Velociraptor',
        classification: 'Predator',
        fleeRate: 0.3,
    },
    {
        id: '16',
        number: '016',
        name: 'Sauropod',
        classification: 'Herbivorous',
        fleeRate: 0.2,
    },
    {
        id: '17',
        number: '017',
        name: 'Ornithomimus',
        classification: 'Omnivores',
        fleeRate: 0.4,
    },
];